### ISSUE TITLE
Improve the PWA functionality of the website

### ISSUE THREAD

**Issue by KushalBhanot** [KushalBhanot/kushalbhanot.github.io#4]
By no means, I'm saying to convert this website into complete PWA. All I'm asking is to increase PWA functionality by some percentage, whatever it may be. 

I hope that this issue will help you learn something new and will be interesting to resolve :)

**Comment by SuNiL-Chau** [comment]
So you want to make the webpage a PWA right?

**Comment by KushalBhanot** [comment]
Yes, @SuNiL-Chau. But I don't mean to burden anyone with a lot of changes. Any updates are welcome 😊🙌🏻

**Comment by SuNiL-Chau** [comment]
That's Fine I think it should max take me 1-hour in which I can at least make it almost ready

**Comment by KushalBhanot** [comment]
That's awesome, @SuNiL-Chau! Glad to see your enthusiasm 🤟🏻⚡️

Go ahead with this issue. I'm assigning it to you.

**Comment by SuNiL-Chau** [comment]
Hey, just check out the PWA it's working on chrome. I'm not having prompt in firefox.

**Comment by KushalBhanot** [comment]
Yes, it's working on Chrome. Thanks for your valuable contribution 😊🙌🏻

#7

**Comment by SuNiL-Chau** [comment]
Your welcome :)
