### ISSUE TITLE
Improve the UI of the Work section

### ISSUE THREAD

**Issue by KushalBhanot** [KushalBhanot/kushalbhanot.github.io#5]
I'm looking for slight changes. Nothing too fancy. It's only meant for beginners to get started with open-source :)

Use your creativity 😊🙌🏻

**Comment by TheNinza** [comment]
Asign me this. I m thinking to include tilt.js with some interactive animations... This would for sure make the website look good

**Comment by KushalBhanot** [comment]
Sure, @TheNinza! Go ahead with it. I'm looking forward to seeing your changes :)
